version: "3"
services:
  opensips:
    container_name: 'opensips'
    image: 'xsdhy/opensips:2.4.11'
    network_mode: host
    volumes:
      - "./opensips.cfg:/usr/local/etc/opensips/opensips.cfg"
      - "./cert/self.pem:/usr/local/etc/opensips/cert/domain.pem"
      - "./self.key:/usr/local/etc/opensips/cert/domain.key"